### ISSUE TITLE
crea compile errors

### ISSUE THREAD

**Issue by preamptive** [fabiaserra/crea#18]
Hi Im new to OFX and github so please bare with me.
Im trying to build the latest version but where can i get all the files including....
helper.cpp, helper.h, vmo.cpp, vmo.h
what is the best working version to download as I cant seem to get the code to compile in xcode 6.4 on osx 10.10.4

Im currently getting Semantic issues in Contour.cpp

/Users/preAk/Documents/OF Projects/of_v0.8.4_osx_release/apps/myApps/crea/src/Contour.cpp:107:19: No member named 'allocate' in 'flowTools::ftDisplayScalar’

/Users/preAk/Documents/OF Projects/of_v0.8.4_osx_release/apps/myApps/crea/src/Contour.cpp:108:19: No member named 'allocate' in 'flowTools::ftVelocityField’

/Users/preAk/Documents/OF Projects/of_v0.8.4_osx_release/apps/myApps/crea/src/Contour.cpp:391:23: No member named 'setSource' in 'flowTools::ftVelocityField’

/Users/preAk/Documents/OF Projects/of_v0.8.4_osx_release/apps/myApps/crea/src/Contour.cpp:444:24: No member named 'getAverageFlow' in 'flowTools::ftOpticalFlow'

Thanks for any advice and help in advance. Keith

**Comment by fabiaserra** [comment]
Hi Keith,

The helper.cpp, helper.h, vmo.cpp, vmo.h are not included in the repository because they are in a research phase. However, they are not necessary to use the tool, just make sure this line in ofApp.h is commented:

``` c
  // include gesture follower files (you need to have vmo.cpp, vmo.h, helper.cpp and helper.h in src)
  #define GESTURE_FOLLOWER
```

The Semantic issues you get are because **ofxFlowTools** and **ofxUI** have been updated since I posted the project and there are some methods that have been renamed. I already changed the calls to these methods and I uploaded the two addons to 'src' so if they do more changes these do not affect the project. Please reinstall the project and it should work fine! :+1: 

Thanks!! :)

**Comment by preamptive** [comment]
That's fantastic thanks for the clarification and fixes! am all up and running now! 😀

**Comment by chetanshetty** [comment]
I am able to run CREA, but, when I enable the second window. All the tabs with get stuck why ? And also I am unable to take the direct input from the Kinect.
